const testMovies = [
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '001',
    nameRU: '«Роллинг Стоунз» в изгнании длинное название 2 строки',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '002',
    nameRU: '«Роллинг Стоунз» в изгнании',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '003',
    nameRU: '«Роллинг Стоунз» в изгнании длинное название 2 строки',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '004',
    nameRU: '«Роллинг Стоунз» в изгнании',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '005',
    nameRU: '«Роллинг Стоунз» в изгнании',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '006',
    nameRU: '«Роллинг Стоунз» в изгнании',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '007',
    nameRU: '«Роллинг Стоунз» в изгнании длинное название 2 строки',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '008',
    nameRU: '«Роллинг Стоунз» в изгнании',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '009',
    nameRU: '«Роллинг Стоунз» в изгнании',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '010',
    nameRU: '«Роллинг Стоунз» в изгнании длинное название 2 строки',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '011',
    nameRU: '«Роллинг Стоунз» в изгнании',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '012',
    nameRU: '«Роллинг Стоунз» в изгнании',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '013',
    nameRU: '«Роллинг Стоунз» в изгнании',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '014',
    nameRU: '«Роллинг Стоунз» в изгнании',
    nameEN: 'Stones in Exile',
  },
  {
    country: 'США',
    director: 'Стивен Кайак ',
    duration: '61',
    year: '2010',
    description: 'В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    trailerLink: 'https://www.youtube.com/watch?v=UXcqcdYABFw',
    thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnPYNBKo1zsT_iRVR5GXpp7n1xgmaaFJdQ1RG0Okcd7r9cRMcP',
    movieId: '015',
    nameRU: '«Роллинг Стоунз» в изгнании',
    nameEN: 'Stones in Exile',
  },
];

const MOVIES_PER_PAGE_1280 = 12;
const MOVIES_PER_PAGE_768 = 8;
const MOVIES_PER_PAGE_320 = 5;

export {
  testMovies, MOVIES_PER_PAGE_1280, MOVIES_PER_PAGE_768, MOVIES_PER_PAGE_320,
};
